const defaultTasks = [
    {
      title: "Finish report",
      body: "Complete the monthly sales report and send it to the manager.",
      priority: "high",
      status: "in-progress",
      estimatedTime: "2",
      timeUnit: "H",
    },
    {
      title: "Buy groceries",
      body: "Pick up groceries for the week, including fruits, vegetables, and dairy.",
      priority: "medium",
      status: "pending",
      estimatedTime: "30",
      timeUnit: "M",
    },
    {
      title: "Clean house",
      body: "Vacuum, dust, and organize the house for a clean living space.",
      priority: "low",
      status: "completed",
      estimatedTime: "1",
      timeUnit: "D",
    },
    {
      title: "Write blog post",
      body: "Write a detailed blog post about productivity tips for remote workers.",
      priority: "medium",
      status: "pending",
      estimatedTime: "4",
      timeUnit: "H",
    },
    {
      title: "Prepare presentation",
      body: "Create a PowerPoint presentation for next week's team meeting.",
      priority: "high",
      status: "in-progress",
      estimatedTime: "3",
      timeUnit: "H",
    },
    {
      title: "Schedule doctor's appointment",
      body: "Book an appointment for a routine checkup with the family doctor.",
      priority: "low",
      status: "completed",
      estimatedTime: "15",
      timeUnit: "M",
    },
    {
      title: "Update resume",
      body: "Revise resume to reflect the latest job experience and skills.",
      priority: "medium",
      status: "pending",
      estimatedTime: "2",
      timeUnit: "H",
    },
    {
      title: "Plan vacation",
      body: "Research and book flights for the summer vacation trip to Hawaii.",
      priority: "high",
      status: "pending",
      estimatedTime: "5",
      timeUnit: "H",
    },
    {
      title: "Finish reading book",
      body: "Complete the final chapters of the self-development book on time management.",
      priority: "low",
      status: "completed",
      estimatedTime: "1",
      timeUnit: "D",
    },
    {
      title: "Attend workshop",
      body: "Participate in the online workshop for career development and networking.",
      priority: "high",
      status: "in-progress",
      estimatedTime: "3",
      timeUnit: "H",
    }
  ];